package com.kamyaabi.event;

public enum OrderEventType {
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_PROCESSING,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    ORDER_FAILED,
    PAYMENT_SUCCESS,
    PAYMENT_PENDING,
    PAYMENT_FAILED
}
