ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_title VARCHAR(255);
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_keywords VARCHAR(500);
ALTER TABLE products ADD COLUMN IF NOT EXISTS og_image_url VARCHAR(500);
ALTER TABLE products ADD COLUMN IF NOT EXISTS canonical_url VARCHAR(500);
